# Generated by Django 4.0.5 on 2022-07-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI_ModelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=1, max_digits=30)),
                ('precison', models.DecimalField(decimal_places=1, max_digits=30)),
                ('loss', models.DecimalField(decimal_places=1, max_digits=30)),
                ('confusion_matrix', models.TextField(max_length=150)),
                ('model', models.BinaryField()),
                ('inserted_on', models.DateField()),
            ],
        ),
    ]
