# Generated by Django 4.0.5 on 2022-06-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.TextField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Feminino')),
                ('peso', models.CharField(max_length=10)),
                ('altura', models.CharField(max_length=10)),
                ('glicemia', models.CharField(max_length=10)),
                ('data', models.DateField()),
            ],
        ),
    ]
