# Generated by Django 4.0.5 on 2022-06-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.TextField(choices=[('m', 'Masculino'), ('f', 'Feminino')])),
                ('peso', models.CharField(max_length=10)),
                ('altura', models.CharField(max_length=10)),
                ('glicemia', models.CharField(max_length=10)),
                ('data', models.DateField()),
            ],
        ),
    ]
