from django.db import models

class DiabetesSamples(models.Model):
    sex = models.IntegerField()
    age1 = models.IntegerField()
    age2 = models.IntegerField()
    age3 = models.IntegerField()
    age4 = models.IntegerField()
    waist1 = models.IntegerField()
    waist2 = models.IntegerField()
    waist3 = models.IntegerField()
    waist4 = models.IntegerField()
    weight = models.IntegerField()
    height = models.CharField(max_length=5)
    imc = models.IntegerField()
    physicalExercise = models.IntegerField()
    hypertensionPills = models.IntegerField()
    fruitsAndVegetables1 = models.IntegerField()
    fruitsAndVegetables2 = models.IntegerField()
    fruitsAndVegetables3 = models.IntegerField()
    diabeticFamily1 = models.IntegerField()
    diabeticFamily2 = models.IntegerField()
    diabeticFamily3 = models.IntegerField()
    diabeticFamily4 = models.IntegerField()
    eatsAlotFats = models.IntegerField()
    smoke1 = models.IntegerField()
    smoke2 = models.IntegerField()
    smoke3 = models.IntegerField()
    smoke4 = models.IntegerField()
    highBloodGlucose1 = models.IntegerField()
    highBloodGlucose2 = models.IntegerField()
    highBloodGlucose3 = models.IntegerField()
    glucoseAnalysis1 = models.IntegerField()
    glucoseAnalysis2 = models.IntegerField()
    glucoseLevelChange1 = models.IntegerField()
    glucoseLevelChange2 = models.IntegerField()
    glucoseLevelChange3 = models.IntegerField()
    womanGlucoseChange1 = models.IntegerField()
    womanGlucoseChange2 = models.IntegerField()
    womanGlucoseChange3 = models.IntegerField()
    womanGlucoseChange4 = models.IntegerField()
    areYouDiabetic = models.IntegerField()


class Contribute(models.Model):
    sex_choices = (('Masculino', 'Masculino'), ('Feminino', 'Feminino'))
    sexo = models.TextField(choices=sex_choices, default='Feminino')
    peso = models.CharField(max_length=10)
    altura = models.CharField(max_length=10)
    glicemia = models.CharField(max_length=10)
    data = models.DateField()
